import React from 'react';


const Home = () => {
    return (
        <div>
            <h1 className='text-red-600'>home</h1>
       
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, adipisci? Soluta eum, atque illo ullam accusamus, odio asperiores magni adipisci inventore sed reiciendis aspernatur ad enim iste, amet in quae neque tempore fuga dolorem accusantium placeat mollitia consectetur? Eum veniam, eaque hic consequuntur harum excepturi vitae velit quas ab corporis sapiente pariatur officiis eveniet error unde nisi. Quod esse dolore id aliquid debitis animi dolor hic ullam vitae impedit enim nostrum consequatur laborum tenetur, provident ipsam quidem odio molestias temporibus possimus, magni officiis, alias quia! Autem error odio delectus culpa voluptates voluptatem laboriosam deserunt nihil quasi, iste vel, modi placeat iusto non quisquam maxime cumque sapiente cum repellendus expedita distinctio minus! Dolorum ipsum explicabo dolores sequi beatae a optio laboriosam pariatur earum. Aut dolore cum non, velit unde dignissimos fugiat a voluptates ipsa dolorum? Nisi quisquam labore facere dignissimos dicta natus exercitationem iure harum dolor porro nemo quasi, saepe recusandae, quae reiciendis delectus nihil quis ipsam. Praesentium eum qui voluptates deserunt earum aliquam blanditiis. Recusandae accusantium eum iste a cupiditate. Exercitationem natus laborum incidunt beatae culpa, eaque reiciendis voluptatibus quidem dolorem. Cum similique velit sunt facilis ullam, maiores numquam delectus cumque id neque libero reprehenderit repudiandae facere fugit odio dolores.</p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat voluptas ipsam ipsum reiciendis, deleniti aspernatur quo numquam aliquam accusantium distinctio esse repudiandae impedit accusamus facere assumenda. Cupiditate vel id quaerat! Perspiciatis eos eaque molestias temporibus fuga et sed quis sint hic necessitatibus tenetur quasi, officiis non aspernatur, in vero tempora. Saepe maxime, assumenda quam expedita beatae corrupti corporis molestiae ipsa? Ad eum sequi sed ea enim autem magni iste, esse quae assumenda dignissimos ipsum tempora, voluptatem dolorem nobis nemo delectus saepe recusandae! Dolores error quos rem expedita. Consequatur, facilis. Nisi debitis minus, suscipit dolore rerum iste, dolores eos molestiae laborum a asperiores fugiat officia deserunt ea sequi possimus omnis doloribus voluptatem quod! Quis officiis officia quae perferendis accusamus molestias obcaecati voluptate aperiam laborum nobis a inventore, ad autem consequatur possimus eligendi! Modi eveniet temporibus adipisci vero iusto? Quis magni harum fugit alias accusamus animi facere nobis doloribus atque ducimus dicta totam porro expedita itaque maxime saepe voluptatem est odit incidunt, dolorem dolor. Aut voluptates voluptatibus repellendus sequi dicta. Totam, perferendis. Officia cum maiores ullam alias animi ex culpa soluta excepturi expedita rerum voluptatibus quo aperiam, saepe sapiente maxime ut eum ea quasi laboriosam. Veniam suscipit adipisci laboriosam omnis! Blanditiis ut aliquid dolorem quae voluptate consequuntur doloribus odit asperiores labore voluptatum doloremque accusamus consectetur dolorum pariatur facilis ipsum perspiciatis atque voluptates recusandae minima, sed quia dicta similique vitae. Dolorem ex distinctio quo soluta. Nostrum eum laboriosam maiores, quidem doloremque mollitia enim illum perferendis odio, sequi quasi deserunt repudiandae commodi tenetur aliquid voluptates eaque molestiae illo ullam beatae vitae. Officiis obcaecati quod voluptate amet nostrum. Architecto doloremque deserunt quo, voluptates hic iste vel. Aspernatur iste inventore ea, vero assumenda animi pariatur voluptas impedit veritatis velit harum laboriosam voluptate doloremque minima vitae sed saepe! Odit, voluptas? Consequuntur nostrum deserunt ab dicta laboriosam dolorem.
        </div>
    );
};

export default Home;